# Generated by Django 5.1.3 on 2024-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0004_remove_questions_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('edit', 'Edit'), ('publish', 'Publish'), ('republish', 'Republish'), ('close', 'Close')], default='Edit', max_length=10),
        ),
    ]
